### ISSUE TITLE
Installation cannot find header file

### ISSUE THREAD

**Issue by j-silver** [copperspice/cs_libguarded#12]
Hello,

I'm trying to install the library on Linux. The compilations runs fine, but when I try to install it ('sudo make install'), installation fails with the message:

```
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/user/Downloads/sources/cs_libguarded/src/test_cow.hpp": No such
  file or directory.
```

Am I doing something wrong?

**Comment by agserm** [comment]
Thanks for your report. This was related to the move from Autotools to CMake, and has just been resolved in 5b84fcf.
