### ISSUE TITLE
surprising directory structure

### ISSUE THREAD

**Issue by daixtrose** [copperspice/cs_libguarded#15]
Compared to other C++ libraries like e.g. [range-v3](https://github.com/ericniebler/range-v3) this repository does not follow the best practice to avoid name clashes by putting headers into a directory that corresponds to the library name. So it is **not** possible to write

```c++
#include <cs_libguarded/some_header.hpp>
```  
I propose to change the directory structure and CMake files such that there is a directory structure similar to

```
├── include
│   └── cs_libguarded
│       ├── header_1.hpp
│       ├── header_2.hpp
│       ├── ...
│       └── header_N.hpp
├── README.md
├── src
│   ├── maybe_implementation_for_header_1.cpp
│   └── etc.cpp
└── test
    ├── CMakeLists.txt
    ├── test_1.cpp
    ├── test_main.cpp
    └── test_N.cpp
```

**Comment by agserm** [comment]
Resolved in a41978e.
