### ISSUE TITLE
libguarded 1.2.0

### ISSUE THREAD

**Issue by ericLemanissier** [copperspice/cs_libguarded#17]
Current cmake file indicates [1.2.0](https://github.com/copperspice/cs_libguarded/blob/master/CMakeLists.txt#L12-L14) but there is only one tag on this repository which is nearly 4 years old: 1.1.0
Do you expect to release a new version of libguarded at some point ?

**Comment by agserm** [comment]
This project is updated on an as-needed basis, tags will be added when appropriate.
