### ISSUE TITLE
rcu_list::emplace has no implementation

### ISSUE THREAD

**Issue by Ozomahtli** [copperspice/cs_libguarded#19]
The implementation of this method is missing!
https://github.com/copperspice/cs_libguarded/blob/f16f2da5934adfe22a04c68340e49ecc7d3fd1f0/src/cs_rcu_list.h#L101

**Comment by agserm** [comment]
Thanks for reporting this, we should have an implementation ready in the next two weeks.

**Comment by agserm** [comment]
Starting to look at this, turns out the implementation is more complex than I initially thought. Will keep you posted.
